config/routes.rb
Rails.application.routes.draw do
  resources :libraries, :responsables, :schools, :groups, :blockeds
  resources :users  do
    collection do
      get 'editPass/:id', action:'editPass', controller:'users', as:'editPass'
      post 'updatePass/:id', action:'updatePass', controller:'users', as:'updatePass'
    end
  #   member do
  #     get 'users/:id', action:'authem'
  #   end
  end
  resources :sessions, only:[:new, :create, :destroy]
  get 'welcome/index'
  get "/login" => "sessions#new", as: "login"
  
  delete "/logout" => "sessions#destroy", as: "logout"
  root to: 'welcome#index'
  resources :books do
    resources :profiles, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :subscriptors do
    get 'credential', to: 'subscriptors#buildCredential'
  end
  resources :borrows, only: [ :index, :new, :create, :getByTitle,  :getByISBN,  :getByAutor,  
  :getByAcc,  :getByName, :findByTitle, :findByISBN, :findByAutor, :findByAcc, :findByName,
  :setReturned] do
    collection do
      get 'getByTitle'
      get 'findByTitle'
      get 'getByISBN'
      get 'findByISBN'
      get 'getByAutor'
      get 'findByAutor'
      get 'getByAcc'
      get 'findByAcc'
      get 'getByName'
      get 'findByName'
      get 'orBorrows'
      get 'srchByName'
      get 'srchFiltered'
      put 'setReturned'
    end
  end
end

app/models/blocked.rb
class Blocked < ActiveRecord::Base
  belongs_to :subscriptor
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :library
  has_one :profile, dependent: :destroy
  has_one :borrow
end

app/models/borrowed.rb
class Borrowed < ActiveRecord::Base
  belongs_to :book
  belongs_to :subscriptor
  
  def self.subscriptor_limit_reached?(subscriptor)
    return true if Borrowed.all.where('subscriptor_id = ?',subscriptor).where(returned:false).count > 2
    return false
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
    belongs_to :library
end

app/models/library.rb
class Library < ActiveRecord::Base
    has_many :users
    has_many :schools
    has_many :subcriptors
    has_many :groups
    has_one :responsable
    has_many :books
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :book
end

app/models/reserved.rb
class Reserved < ActiveRecord::Base
  belongs_to :book
  belongs_to :subscriptor
end

app/models/responsable.rb
class Responsable < ActiveRecord::Base
  belongs_to :library
end

app/models/returned.rb
class Returned < ActiveRecord::Base
  belongs_to :book
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :library
end

app/models/subscriptor.rb
class Subscriptor < ActiveRecord::Base
  mount_uploader :picture, MyPictureUploader
  belongs_to :group
  belongs_to :school
  has_many :borrows
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :fullname, :email, presence: true

  
  def self.valid_password?(pretended,usr)
    if usr.authenticate(pretended)
      return true
    else
      usr.errors.add(:authme,'Error revise que tenga los datos correctos')
      return false
    end
  end
  
  def self.equalPass?(pass,confirm,usr)
    if pass == confirm
      return true
    else
      usr.errors.add(:password_confirmation, 'Error los passwords no coinciden') 
      return false
    end
  end
end

app/controllers/blockeds_controller.rb
class BlockedsController < ApplicationController
  before_action :set_blocked, only: [:show, :edit, :update, :destroy]

  # GET /blockeds
  # GET /blockeds.json
  def index
    @blockeds = Blocked.all
  end

  # GET /blockeds/1
  # GET /blockeds/1.json
  def show
  end

  # GET /blockeds/new
  def new
    @blocked = Blocked.new
  end

  # GET /blockeds/1/edit
  def edit
  end

  # POST /blockeds
  # POST /blockeds.json
  def create
    @blocked = Blocked.new(blocked_params)

    respond_to do |format|
      if @blocked.save
        format.html { redirect_to @blocked, notice: 'Blocked was successfully created.' }
        format.json { render :show, status: :created, location: @blocked }
      else
        format.html { render :new }
        format.json { render json: @blocked.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blockeds/1
  # PATCH/PUT /blockeds/1.json
  def update
    respond_to do |format|
      if @blocked.update(blocked_params)
        format.html { redirect_to @blocked, notice: 'Blocked was successfully updated.' }
        format.json { render :show, status: :ok, location: @blocked }
      else
        format.html { render :edit }
        format.json { render json: @blocked.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blockeds/1
  # DELETE /blockeds/1.json
  def destroy
    @blocked.destroy
    respond_to do |format|
      format.html { redirect_to blockeds_url, notice: 'Blocked was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blocked
      @blocked = Blocked.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blocked_params
      params.require(:blocked).permit(:subscriptor_id, :end, :notes)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blockeds_helper.rb
module BlockedsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blockeds/_form.html.erb
<div class='container have_border_heroku full_borders be-soft_gray'>
  <div class='row'>
    <%= bootstrap_form_for(@blocked, layout: :horizontal) do |f| %>
      <% if @blocked.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@blocked.errors.count, "error") %> prohibited this blocked from being saved:</h2>
    
          <ul>
          <% @blocked.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
    </div>
      <% end %>
      <%= f.collection_select_with_bootstrap :subscriptor_id, Subscriptor.all, :id, :fullname, label:'Subscriptor', control_col:'col-xd col-md-4' %>
      <%= f.text_field_with_bootstrap :end, label:'Bloqueo finaliza:', control_col:'col-xs col-md-2', class:'xdate' %>
      <%= f.text_area_with_bootstrap :notes, label:'Comentarios', control_col:'col-xs col-md-8' %>
      <div class='col-xs-2 col-md-2'>
        <%= f.submit 'APLICAR', control_col:'col-xs col-md-2', class:'btn btn-md btn-block be-border_heroku' %>
      </div>
    <% end %>
  </div>
</div>

app/views/blockeds/edit.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-12 col-md-12'>
            <h1>Editar Subscriptor Bloqueado</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<div class='container'>
    <div class='row'>
        <div class='col-xs-4 col-md-4'></div>
        <div class='col-xs-2 col-md-2'>
            <%= link_to 'Mostrar', @blocked, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
        <div class='col-xs-2 col-md-2'>
            <%= link_to 'Regresar', blockeds_path, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
    </div>
</div>

app/views/blockeds/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <h1>Subscriptores Bloqueados</h1>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-xs col-md-2'>
      <%= link_to 'Bloquear', new_blocked_path, class:'btn btn-default btn-block' %><br>
      <%= link_to 'Regresar', subscriptors_path, class:'btn btn-default btn-block' %>
    </div>
    <div class='col-xs col-md-8'>
      <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>Subscriptor</th>
              <th>Fecha Termino</th>
              <th>Notas</th>
              <th colspan="2"></th>
            </tr>
          </thead>
          <tbody>
            <% @blockeds.each do |blocked| %>
              <tr>
                <td><%= blocked.subscriptor.fullname %></td>
                <td><%= blocked.end %></td>
                <td><%= blocked.notes %></td>
                <td><%= link_to edit_blocked_path(blocked), class:'btn btn-xs' do %>
                    <%= octicon 'pencil', class:'rigth' %>
                    <% end %>
                </td>
                <td><%= link_to blocked, method: :delete, data: { confirm: 'Eliminar de bloqueados?' }, class:'btn btn-xs'  do %>
                      <%= octicon 'trashcan', class:'rigth' %>
                    <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/blockeds/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-12 col-md-12'>
            <h1>Nuevo Subscriptor Bloqueado</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<div class='container'>
    <div class='row'>
        <div class='col-xs-4 col-md-2'>
            <%= link_to 'Regresar', blockeds_path, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
    </div>
</div>

app/views/blockeds/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs col-md-4'>
      <p>
        <strong>Subscriptor:</strong>
        <%= @blocked.subscriptor.fullname %>
      </p>
    </div>
    <div class='col-xs col-md-3'>
      <p>
        <strong>End:</strong>
        <%= @blocked.end %>
      </p>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-8'>
      <p>
        <strong>Notes:</strong>
        <%= @blocked.notes %>
      </p>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-xs-3 col-md-2'>
      <%= link_to 'Edit', edit_blocked_path(@blocked), class:'btn btn-md btn-block be-purple_strong' %> 
    </div>
    <div class='col-xs-3 col-md-2'>
      <%= link_to 'Back', blockeds_path, class:'btn btn-md btn-block be-purple_strong' %>
    </div>
  </div>
</div>