config/routes.rb
Rails.application.routes.draw do
  resources :libraries, :responsables, :schools, :groups, :blockeds
  resources :users  do
    collection do
      get 'editPass/:id', action:'editPass', controller:'users', as:'editPass'
      post 'updatePass/:id', action:'updatePass', controller:'users', as:'updatePass'
    end
  #   member do
  #     get 'users/:id', action:'authem'
  #   end
  end
  resources :sessions, only:[:new, :create, :destroy]
  get 'welcome/index'
  get "/login" => "sessions#new", as: "login"
  
  delete "/logout" => "sessions#destroy", as: "logout"
  root to: 'welcome#index'
  resources :books do
    resources :profiles, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :subscriptors do
    get 'credential', to: 'subscriptors#buildCredential'
  end
  resources :borrows, only: [ :index, :new, :create, :getByTitle,  :getByISBN,  :getByAutor,  
  :getByAcc,  :getByName, :findByTitle, :findByISBN, :findByAutor, :findByAcc, :findByName,
  :setReturned] do
    collection do
      get 'getByTitle'
      get 'findByTitle'
      get 'getByISBN'
      get 'findByISBN'
      get 'getByAutor'
      get 'findByAutor'
      get 'getByAcc'
      get 'findByAcc'
      get 'getByName'
      get 'findByName'
      get 'orBorrows'
      get 'srchByName'
      get 'srchFiltered'
      put 'setReturned'
    end
  end
end

app/models/blocked.rb
class Blocked < ActiveRecord::Base
  belongs_to :subscriptor
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :library
  has_one :profile, dependent: :destroy
  has_one :borrow
end

app/models/borrowed.rb
class Borrowed < ActiveRecord::Base
  belongs_to :book
  belongs_to :subscriptor
  
  def self.subscriptor_limit_reached?(subscriptor)
    return true if Borrowed.all.where('subscriptor_id = ?',subscriptor).where(returned:false).count > 2
    return false
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
    belongs_to :library
end

app/models/library.rb
class Library < ActiveRecord::Base
    has_many :users
    has_many :schools
    has_many :subcriptors
    has_many :groups
    has_one :responsable
    has_many :books
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :book
end

app/models/reserved.rb
class Reserved < ActiveRecord::Base
  belongs_to :book
  belongs_to :subscriptor
end

app/models/responsable.rb
class Responsable < ActiveRecord::Base
  belongs_to :library
end

app/models/returned.rb
class Returned < ActiveRecord::Base
  belongs_to :book
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :library
end

app/models/subscriptor.rb
class Subscriptor < ActiveRecord::Base
  mount_uploader :picture, MyPictureUploader
  belongs_to :group
  belongs_to :school
  has_many :borrows
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :fullname, :email, presence: true

  
  def self.valid_password?(pretended,usr)
    if usr.authenticate(pretended)
      return true
    else
      usr.errors.add(:authme,'Error revise que tenga los datos correctos')
      return false
    end
  end
  
  def self.equalPass?(pass,confirm,usr)
    if pass == confirm
      return true
    else
      usr.errors.add(:password_confirmation, 'Error los passwords no coinciden') 
      return false
    end
  end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: [:show, :edit, :update, :destroy]

  # GET /libraries
  # GET /libraries.json
  def index
    @libraries = Library.all
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  # GET /libraries/1/edit
  def edit
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(library_params)

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Biblioteca creada satisfactoriamente!.' }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1
  # PATCH/PUT /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to @library, notice: 'Biblioteca actualizada satisfactoriamente!.' }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: 'Biblioteca borrada satisfactoriamente!.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def library_params
      params.require(:library).permit(:name, :address, :telephone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blockeds_helper.rb
module BlockedsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/libraries/_form.html.erb
<%= bootstrap_form_for(@library) do |f| %>
  <% if @library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@library.errors.count, "error") %> No se pudo salvar!:</h2>
      <ul>
      <% @library.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='container'>
    <div class='row'>
      <div class='col-xs-1 col-md-1'>
        <%= f.text_field_with_bootstrap :number, label:'No. de Biblioteca' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs-4 col-md-3'>
        <%= f.text_field_with_bootstrap :name, label:'Nombre'%>
      </div>
      <div class='col-xs-4 col-md-7'>
        <%= f.text_field_with_bootstrap :address, label:'Direccion' %>
      </div>
      <div class='col-xs-2 col-md-2'>
        <%= f.telephone_field_with_bootstrap :telephone, label:'Telefono(s)' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs-3 col-md-3'>
        <%= f.submit 'SALVAR', class:'btn btn-md be-border_heroku btn-block' %>
      </div>
    </div>
  </div>
<% end %>

app/views/libraries/edit.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-12 col-md-12'>
            <h1>Editar Biblioteca</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<div class='container'>
    <div class='row'>
        <div class='col-xs-2 col-md-2'>
            <%= link_to 'Mostrar', @library, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
        <div class='col-xs-2 col-md-2'>
            <%= link_to 'Regresar', libraries_path, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
    </div>
</div>

app/views/libraries/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <h1>Lista de Bibliotecas</h1>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-xs-8 col-md-12'>
      <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Direccion</th>
              <th>Telefono(s)</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @libraries.each do |library| %>
              <tr>
                <td><%= library.name %></td>
                <td><%= library.address %></td>
                <td><%= library.telephone %></td>
                <td><%= link_to '', library, title:'mostrar', rel:'tooltip', 
                    class:'btn btn-sm btn-default btn-block glyphicon glyphicon-file' %></td>
                <td><%= link_to '', edit_library_path(library), title:'editar', rel:'tooltip',
                    class:'btn btn-sm btn-default btn-block glyphicon glyphicon-edit' %></td>
                <td><%= link_to '', library, method: :delete, data: { confirm: 'Esta usted seguro?' },
                    title:'borrar', rel:'tooltip',
                    class:'btn btn-sm btn-default btn-block glyphicon glyphicon-trash'%></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-3 col-md-3'>
      <%= link_to 'Nueva Biblioteca', new_library_path, class:'btn btn-xs btn-default btn-block' %>
    </div>
  </div>
</div>

app/views/libraries/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-12 col-md-12'>
            <h1>Nueva Biblioteca</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<div class='container'>
    <div class='row'>
        <div class='col-xs-4 col-md-4'>
            <%= link_to 'Regresar', libraries_path, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
    </div>
</div>

app/views/libraries/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-8 col-md-8'>
      <p>
        <strong>Nombre:</strong>
        <%= @library.name %>
      </p>
      <p>
        <strong>Direccion:</strong>
        <%= @library.address %>
      </p>
      <p>
        <strong>Telefono(s):</strong>
        <%= @library.telephone %>
      </p>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-xs-3 col-md-2'>
      <%= link_to 'Editar', edit_library_path(@library),class:'btn btn-md btn-block be-purple_strong' %>
    </div>
    <div class='col-xs-3 col-md-2'>
      <%= link_to 'Regresar', libraries_path,class:'btn btn-md btn-block be-purple_strong' %>  
    </div>
  </div>
</div>