config/routes.rb
Rails.application.routes.draw do
  resources :libraries, :responsables, :schools, :groups, :blockeds
  resources :users  do
    collection do
      get 'editPass/:id', action:'editPass', controller:'users', as:'editPass'
      post 'updatePass/:id', action:'updatePass', controller:'users', as:'updatePass'
    end
  #   member do
  #     get 'users/:id', action:'authem'
  #   end
  end
  resources :sessions, only:[:new, :create, :destroy]
  get 'welcome/index'
  get "/login" => "sessions#new", as: "login"
  
  delete "/logout" => "sessions#destroy", as: "logout"
  root to: 'welcome#index'
  resources :books do
    resources :profiles, only: [:new, :create, :destroy, :edit, :update]
  end
  resources :subscriptors do
    get 'credential', to: 'subscriptors#buildCredential'
  end
  resources :borrows, only: [ :index, :new, :create, :getByTitle,  :getByISBN,  :getByAutor,  
  :getByAcc,  :getByName, :findByTitle, :findByISBN, :findByAutor, :findByAcc, :findByName,
  :setReturned] do
    collection do
      get 'getByTitle'
      get 'findByTitle'
      get 'getByISBN'
      get 'findByISBN'
      get 'getByAutor'
      get 'findByAutor'
      get 'getByAcc'
      get 'findByAcc'
      get 'getByName'
      get 'findByName'
      get 'orBorrows'
      get 'srchByName'
      get 'srchFiltered'
      put 'setReturned'
    end
  end
end

app/models/blocked.rb
class Blocked < ActiveRecord::Base
  belongs_to :subscriptor
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :library
  has_one :profile, dependent: :destroy
  has_one :borrow
end

app/models/borrowed.rb
class Borrowed < ActiveRecord::Base
  belongs_to :book
  belongs_to :subscriptor
  
  def self.subscriptor_limit_reached?(subscriptor)
    return true if Borrowed.all.where('subscriptor_id = ?',subscriptor).where(returned:false).count > 2
    return false
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
    belongs_to :library
end

app/models/library.rb
class Library < ActiveRecord::Base
    has_many :users
    has_many :schools
    has_many :subcriptors
    has_many :groups
    has_one :responsable
    has_many :books
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :book
end

app/models/reserved.rb
class Reserved < ActiveRecord::Base
  belongs_to :book
  belongs_to :subscriptor
end

app/models/responsable.rb
class Responsable < ActiveRecord::Base
  belongs_to :library
end

app/models/returned.rb
class Returned < ActiveRecord::Base
  belongs_to :book
end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :library
end

app/models/subscriptor.rb
class Subscriptor < ActiveRecord::Base
  mount_uploader :picture, MyPictureUploader
  belongs_to :group
  belongs_to :school
  has_many :borrows
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :fullname, :email, presence: true

  
  def self.valid_password?(pretended,usr)
    if usr.authenticate(pretended)
      return true
    else
      usr.errors.add(:authme,'Error revise que tenga los datos correctos')
      return false
    end
  end
  
  def self.equalPass?(pass,confirm,usr)
    if pass == confirm
      return true
    else
      usr.errors.add(:password_confirmation, 'Error los passwords no coinciden') 
      return false
    end
  end
end

app/controllers/subscriptors_controller.rb
class SubscriptorsController < ApplicationController
  before_action :set_subscriptor, only: [:show, :edit, :update, :destroy]

  # GET /subscriptors
  # GET /subscriptors.json
  def index
    @subscriptors = Subscriptor.all
  end

  # GET /subscriptors/1
  # GET /subscriptors/1.json
  def show
  end

  # GET /subscriptors/new
  def new
    @subscriptor = Subscriptor.new
  end

  # GET /subscriptors/1/edit
  def edit
  end

  # POST /subscriptors
  # POST /subscriptors.json
  def create
    @subscriptor = Subscriptor.new(subscriptor_params)
    byebug
    respond_to do |format|
      if @subscriptor.save
        format.html { redirect_to @subscriptor, notice: 'Subscriptor creado satisfactoriamente!.' }
        format.json { render :show, status: :created, location: @subscriptor }
      else
        format.html { render :new }
        format.json { render json: @subscriptor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptors/1
  # PATCH/PUT /subscriptors/1.json
  def update
    respond_to do |format|
      if @subscriptor.update(subscriptor_params)
        format.html { redirect_to @subscriptor, notice: 'Subscriptor actualizado satisfactoriamente!.' }
        format.json { render :show, status: :ok, location: @subscriptor }
      else
        format.html { render :edit }
        format.json { render json: @subscriptor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptors/1
  # DELETE /subscriptors/1.json
  def destroy
    @subscriptor.destroy
    respond_to do |format|
      format.html { redirect_to subscriptors_url, notice: 'Subscriptor borrado satisfactoriamente!.' }
      format.json { head :no_content }
    end
  end
  
  def buildCredential
    @subscriptor = Subscriptor.find(params[:subscriptor_id])
    #byebug
    respond_to do |format|
      format.pdf do
        
        pdf = Credential.new(@subscriptor)
        
        send_data pdf.render, 
          filename: "credencial-#{@subscriptor.id}.pdf",
          type: 'application/pdf',
          disposition: 'inline'
      end
    end
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscriptor
      @subscriptor = Subscriptor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscriptor_params
      params.require(:subscriptor).permit(:account, :fullname, :group_id, :school_id, :email, :address, :colony, :city, :state, :cp, :telephone, :celular, :picture, :notes, :vigencyStart, :vigencyEnd, :age, :gurantor)
    end
    
end

app/helpers/blockeds_helper.rb
module BlockedsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/borrows_helper.rb
module BorrowsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subscriptors_helper.rb
module SubscriptorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/subscriptors/_form.html.erb
<%= bootstrap_form_for(@subscriptor, html:{multipart:true}) do |f| %>
  <% if @subscriptor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriptor.errors.count, "error") %> No se pudo salvar!:</h2>

      <ul>
      <% @subscriptor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='container'>
    <div class='row'>
      <div class='col-xs col-md-3'>
          <%= image_tag @subscriptor.picture, class:'img-fluid card'  %>
          <%= f.file_field :picture, label:'Foto' %>
      </div>
      <div class='col-xs col-md-1'>
        <%= f.text_field_with_bootstrap :account, label:'cuenta' %>
      </div>
      <div class='col-xs col-md-3'>
        <%= f.text_field_with_bootstrap :fullname, label:'Nombre Completo' %>
      </div>
      <div class='col-xs col-md-4'>
        <%= f.collection_select_with_bootstrap :school_id, School.all, :id, :name, label:'Escuela'  %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs col-md-3'>
        <%= f.collection_select_with_bootstrap :group_id, Group.all, :id, :description, label:'Grupo'  %>
      </div> 
      <div class='col-xs col-md-4'>
        <%= f.email_field_with_bootstrap :email, label:'Correo Electronico' %>
      </div>
      <div class='col-xs col-md-4'>
        <%= f.text_field_with_bootstrap :address, label:'Direccion' %>
      </div>
      <div class='col-xs col-md-4'>
        <%= f.text_field_with_bootstrap :colony, label:'Colonia' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs col-md-2'>
        <%= f.text_field_with_bootstrap :city, label:'Ciudad' %>
      </div>
      <div class='col-xs col-md-2'>
        <%= f.text_field_with_bootstrap :state, label:'Estado' %>
      </div>
      <div class='col-xs col-md-1'>
        <%= f.text_field_with_bootstrap :cp, label:'C.P.' %>
      </div>
      <div class='col-xs col-md-2'>
        <%= f.phone_field_with_bootstrap :telephone, label:'Telefono Fijo' %>
      </div>
      <div class='col-xs col-md-2'>
        <%= f.phone_field_with_bootstrap :celular %>
      </div>
      <div class='col-xs col-md-3'>
        <%= f.text_area_with_bootstrap :notes, label:'Comentarios' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs col-md-3'>
        <%= f.date_field_with_bootstrap :vigencyStart, label:'Inicio Vigencia', class:'xdate' %>
      </div>
      <div class='col-xs col-md-3'>
        <%= f.date_field_with_bootstrap :vigencyEnd, label:'Fin Vigencia', class:'xdate' %>
      </div>
      <div class='col-xs col-md-1'>
        <%= f.number_field_with_bootstrap :age, label:'Edad' %>
      </div>
      <div class='col-xs col-md-4'>
        <%= f.text_field_with_bootstrap :gurantor, label:'Fiador' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-xs-4 col-md-4'></div>
      <div class='col-xs col-md-4'>
         <%= f.submit 'SALVAR', class:'btn btn-md be-border_heroku btn-block' %>
      </div>
    </div>
  </div>
  <%#= f.methods.grep /bootstrap/ %>
<% end %>

app/views/subscriptors/edit.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-12 col-md-12'>
            <h1>Editar SUbscriptor</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<div class='container'>
    <div class='row'>
        <div class='col-xs-4 col-md-4'></div>
        <div class='col-xs-2 col-md-2'>
            <%= link_to 'Mostrar', @subscriptor, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
        <div class='col-xs-2 col-md-2'>
            <%= link_to 'Regresar', subscriptors_path, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
    </div>
</div>

app/views/subscriptors/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-xs-12 col-md-12'>
      <h1>Listado Subscriptores</h1>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-3'>
      <%= link_to 'Subscriptores Bloqueados', blockeds_path, class:'btn btn-default btn-block' %>
    </div>
  </div>
</div>
<div class="container">
  <div class='row'>
    <div class='col-xs-10 col-md-12'>
      <div class="table-responsive">
        <table class="table table-hover table-striped">
          <thead>
            <tr>
              <th>Cuenta</th>
              <th>Nombre Completo</th>
              <!--<th>Groupo</th>
              <th>Escuela</th>-->
              <th>Email</th>
              <th>Dirección</th>
              <!--<th>Colonia</th>
              <th>Ciudad</th>
              <th>Estado</th>
              <th>C.P.</th>-->
              <th>Telefono Casa</th>
              <th>Celular</th>
              <!--<th>Foto</th>
              <th>Notas</th>
              <th>Inicio Vigencia</th>
              <th>Fin Vigencia</th>
              <th>Edad</th>
              <th>Fiador</th>-->
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @subscriptors.each do |subscriptor| %>
              <tr>
                <td><%= subscriptor.account %></td>
                <td><%= subscriptor.fullname %></td>
                <!--<td><%#= subscriptor.group.description %></td>
                <td><%#= subscriptor.school.name %></td>-->
                <td><%= subscriptor.email %></td>
                <td><%= subscriptor.address %></td>
                <!--<td><%#= subscriptor.colony %></td>
                <td><%#= subscriptor.city %></td>
                <td><%#= subscriptor.state %></td>
                <td><%#= subscriptor.cp %></td> -->
                <td><%= subscriptor.telephone %></td>
                <td><%= subscriptor.celular %></td>
                <!--<td><%#= subscriptor.picture %></td>
                <td><%#= subscriptor.notes %></td>
                <td><%#= subscriptor.vigencyStart %></td>
                <td><%#= subscriptor.vigencyEnd %></td>
                <td><%#= subscriptor.age %></td>
                <td><%#= subscriptor.gurantor %></td> -->
                <td><%= link_to '', subscriptor, title:'mostrar', rel:'tooltip', 
                        class:'btn btn-sm btn-block btn-default glyphicon glyphicon-file' %></td>
                <td><%= link_to '', edit_subscriptor_path(subscriptor), title:'editar', rel:'tooltip',
                        class:'btn btn-sm btn-block btn-default glyphicon glyphicon-edit' %></td>
                <td><%= link_to '', subscriptor, method: :delete, data: { confirm: 'Esta usted seguro?' }, title:'borrar', rel:'tooltip',
                        class:'btn btn-sm btn-block btn-default glyphicon glyphicon-trash' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-8 col-md-3'>
      <%= link_to 'Nuevo(a) Subscriptor(a)', new_subscriptor_path, class:'btn  btn-default btn-block' %>
    </div>
  </div>
</div>

app/views/subscriptors/new.html.erb
<div class='container'>
    <div class='row'>
        <div class='col-xs-12 col-md-12'>
            <h1>Nuevo Subscriptor</h1>
        </div>
    </div>
</div>
<%= render 'form' %>
<div class='container'>
    <div class='row'>
        <div class='col-xs-4 col-md-4'></div>
        <div class='col-xs col-md-4'>
            <%= link_to 'Regresar', subscriptors_path, class:'btn btn-md btn-block be-purple_strong' %>
        </div>
    </div>
</div>

app/views/subscriptors/show.html.erb
<div class='container be-round_ligth_gray'>
  <div class='row'>
    <div class='col-xs col-md-3'>
      <%= image_tag @subscriptor.picture, class:'img-fluid card'  %>
      <div class='card-block be-border_heroku'>
        <h4 class='title-small'>
          <strong><%= @subscriptor.fullname %></strong><br>
          <%= @subscriptor.email %>
        </h4>
      </div>
    </div>
    <div class='col-xs col-md-9'>
      <div class='row'>
        <div class='col-xs'>
          <strong>Cuenta: </strong>
          <%= @subscriptor.account %>
        </div>
        <div class='col-xs'>
          <strong>Grupo:</strong>
          <%#= @subscriptor.group.description %>
        </div>
        <div class='col-xs'>
          <strong>Escuela:</strong>
          <%#= @subscriptor.school.shortname %>
        </div>
        <div class='col-xs'>
          <strong>Dirección: </strong><%= @subscriptor.address %>
        </div>
        <div class='col-xs'>
          <strong>Colonia: </strong><%= @subscriptor.colony %>
       </div>
        <div class='col-xs'>
          <strong>C.P. </strong>
          <%= @subscriptor.cp %>
        </div>
        <div class='col-xs'>
            <strong>Ciudad: </strong>
            <%= @subscriptor.city %>
        </div>
        <div class='col-xs'>
          <strong>Estado: </strong>
          <%= @subscriptor.state %>
        </div>
        <div class='col-xs'>
          <strong>Telefono Fijo: </strong>
          <%= @subscriptor.telephone %>
        </div>
        <div class='col-xs'>
          <strong>Celular: </strong>
          <%= @subscriptor.celular %>
        </div>
        <div class='col-xs'>
          <strong>Edad: </strong><br>
          <%= @subscriptor.age %>
        </div>
     </div>
      <div class='row'>
        <div class='col-xs col-md-2'>
          <strong>Inicio Vigencia: </strong>
          <%= @subscriptor.vigencyStart %>
        </div>
        <div class='col-xs col-md-2'>
          <strong>Fin Vigencia:</strong>
          <%= @subscriptor.vigencyEnd %>
        </div>
        <div class='col-xs col-md-4'>
          <strong>Fiador:</strong><br>
          <%= @subscriptor.gurantor %>
        </div>
      </div>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-8'>
      <p>
        <strong>Notas</strong><br>
        <%= @subscriptor.notes %><br>
      </p>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs col-md-4'>
      <%= link_to ' CREDENCIAL', subscriptor_credential_path(@subscriptor.id, format:"pdf"), class:'btn btn-md btn-block btn-default btn-transparent be-border_heroku' %>
      <br>
    </div>
  </div>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-md-4'></div>
    <div class='col-xs col-md-2'>
      <%= link_to 'Editar', edit_subscriptor_path(@subscriptor), class:'btn btn-md btn-block be-purple_strong' %>
    </div>
    <div class='col-xs col-md-2'>
      <%= link_to 'Regresar', subscriptors_path, class:'btn btn-md btn-block be-purple_strong' %>  
    </div>
  </div>
</div>